services:
  - type: web
    name: powerbank-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    region: oregon
    autoDeploy: true
    plan: free
    envVars:
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false
      - key: PUBLIC_BASE_URL
        sync: false
      - key: MQTT_HOST
        sync: false
      - key: MQTT_PORT
        value: "1883"
      - key: MQTT_TOPIC_PREFIX
        value: powerbank

